// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXalfPcjjSyJfWg6VXV6GXmCUBQ5p_oZo',
    appId: '1:872979470489:web:2de943672c085040b64008',
    messagingSenderId: '872979470489',
    projectId: 'pos-app-aa627',
    authDomain: 'pos-app-aa627.firebaseapp.com',
    storageBucket: 'pos-app-aa627.appspot.com',
    measurementId: 'G-5RXEF9DBCF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeUiEH73Io-sYKEGEXf0EFQ5Z7acByqmw',
    appId: '1:872979470489:android:e15021e27a0aa79fb64008',
    messagingSenderId: '872979470489',
    projectId: 'pos-app-aa627',
    storageBucket: 'pos-app-aa627.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTfOrcA7xskCGl8jd8FNz0nC3v3Nl6M-k',
    appId: '1:872979470489:ios:74713dcf2a961bc7b64008',
    messagingSenderId: '872979470489',
    projectId: 'pos-app-aa627',
    storageBucket: 'pos-app-aa627.appspot.com',
    iosBundleId: 'com.Devmaker.posApp',
  );
}
